language: node_js
node_js:
  - '10'
on: branche:dev
cache:
  directories:
    - node_modules
deploy:

before_script:
  - 'npm i -g gatsby'
  - 'npm ci'
script:
  - 'npm run test'
after_success:
  - 'npm run deploy'
